# Generated by Django 4.1.5 on 2023-02-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertreviewapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
        migrations.AddField(
            model_name='registration',
            name='addressone',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='addresstwo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='c_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='district',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='pincode',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobileno',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
