# Generated by Django 4.1.5 on 2023-02-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertreviewapp', '0003_registration_dob_registration_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=100, null=True)),
                ('Brand_Name', models.CharField(max_length=100, null=True)),
                ('Car_Name', models.CharField(max_length=100, null=True)),
                ('Model_Name', models.CharField(max_length=100, null=True)),
                ('Seat', models.CharField(max_length=50, null=True)),
                ('Fuel', models.CharField(max_length=100, null=True)),
                ('Price', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
