# Generated by Django 4.1.5 on 2023-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertreviewapp', '0002_car_expert_remove_registration_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
