# Generated by Django 4.1.5 on 2023-03-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertreviewapp', '0003_expert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='expert',
            name='confirm_password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='experience',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='mobilenumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expert',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
